# Generated by Django 2.1.3 on 2018-12-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0003_auto_20181207_1019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employees',
            name='age',
            field=models.IntegerField(default=20),
        ),
    ]
