# Generated by Django 2.1.3 on 2018-12-27 22:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0005_auto_20181227_2328'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employees',
            old_name='birthdays',
            new_name='birthday',
        ),
    ]
