# Generated by Django 2.1.3 on 2019-01-07 12:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapi', '0006_auto_20181227_2333'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employees',
            name='age',
        ),
    ]
